name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.0

      - name: Set up Go
        uses: actions/setup-go@v6.5.0
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Install dependencies
        run: go mod tidy

      - name: Build
        run: make build

      - name: Run tests
        run: make test

      - name: Run linters
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          version: v2.11.4

  generate:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.0

      - name: Set up Go
        uses: actions/setup-go@v6.5.0
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Generate docs
        run: |
          go install github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs@latest
          export PATH="$(go env GOPATH)/bin:$PATH"
          make docs

      - name: Check docs are up to date
        run: |
          git diff --compact-summary --exit-code || \
            (echo; echo "docs/ is out of date. Run 'make docs' and commit the result."; exit 1)
